{% set name = "hyperion" %}
{% set version = "0.9.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Hyperion-{{ version }}.tar.gz
  sha256: f80d62ee9212244aa39a2c59c3b6a767eb587a58883234122e790d5f383c9690

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - numpy
  run:
    - hyperion-fortran 0.9.10
    - python
    - {{ pin_compatible('numpy') }}
    - matplotlib-base >=1.5
    - h5py >=2.4
    - astropy >=1.2

    # We need to exclude yt 3.3.0 and 3.3.1 because they include a
    # bug that causes Hyperion to not work properly when dealing with
    # octree grids.
    - yt >=3.2,!=3.3.0,!=3.3.1

test:
  imports:
    - hyperion
    - hyperion.util.interpolate
  commands:
    - hyperion --help
    - pip check
  requires:
    - pip

about:
  home: http://www.hyperion-rt.org
  summary: Monte-Carlo Radiative Transfer Code
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - astrofrog
