{% set name = "hyperion" %}
{% set version = "0.9.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hyperion-{{ version }}.tar.gz
  sha256: 097a4746ff2f054b6520e6811651605b85230461c541c97ad10d1c4ba6c7533c

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - setuptools-scm >=6.2
    - numpy
    - pip
  run:
    - hyperion-fortran 0.9.11
    - python
    - matplotlib-base >=1.5
    - astropy >=1.2
    - h5py >=2.4
    - decorator
    - {{ pin_compatible('numpy') }}
    - yt >=3.2

test:
  imports:
    - hyperion
    - hyperion.util.interpolate
  commands:
    - pip check
    - hyperion --help
  requires:
    - pip

about:
  home: http://www.hyperion-rt.org
  summary: Monte-Carlo Radiative Transfer Code
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - astrofrog
