travis:
  secure:
    BINSTAR_TOKEN: lntDJ1zh1j0PDmJ1CX7CPpDW4ec3kmhv67VJ1lEdxgJaySxBuBM2pYsacaAIeVXEXpH8QdfeXveOCUdbHoHWe22pCyxx5nLPnfjTulupzIrArjz151DK1eySodX9e+gO7dFcCpEgrHXVU3tkDSRQfxdb88ihT9nAkU8B8r97AaKJh2L1SYAnK+DdCyLnVtztz7Ejxb7P1TZFcdeKJq1UNQxe1U7SFgj8HsVzklAC1t/+hK5nrEYoNtOAV61I/K5MG9G9gzok0b7/uxNooOUAgma0ZUB5j96XKxRCxenzuBMRlATLftbFdePeiVaw/txE+eGygutfSacdyX6UIZcsYbUIbqcfWWVMFkonN6JDsMu+Wvfv40gJekIxQA1Nam6VBeTSyCG5zEXfPjycKYyl3BoqleRnIlxy76Olp+0Agu2kN9ClwiKb5PvCSaXNbV0q4JXpb5O7ZZ+UtSQ7EogTw9Cr9JqezqgLTTdN8f3GbwHYq48ERZ3Z3aPuFrYOmF6YXFS2cKlBQG+22eL9p49HF7H1rTV+z1qslWqPwAH2g9mo8CuJ6KNpuWhOJv4ng4Fxmb/xa3VwFzTVybB2muRaulbac4T1pbSoclIEspQXLBWLj8dCOxkITU7EsDf2svXMgAm+AnMURsTNX2pwDobYiEcTHFgpj7XdQzu07aYjC10=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
